CREATE TABLE `neighbouring_countries`(
	`neighbour1` varchar(32) NOT NULL,
	`neighbour2` varchar(32) NOT NULL
);
INSERT INTO neighbouring_countries
	(neighbour1, neighbour2)
VALUES
	('Albania', 'Greece'),
	('Albania', 'Kosovo'),
	('Albania', 'Macedonia'),
	('Albania', 'Montenegro'),
	('Andorra', 'France'), 
	('Andorra', 'Spain'),
	('Armenia', 'Azerbaijan'),
	('Armenia', 'Georgia'),
	('Armenia', 'Turkey'),
	('Austria', 'Czech Republic'),
	('Austria', 'Germany'),
	('Austria', 'Hungary'),
	('Astria', 'Italy'),
	('Austria', 'Liechtenstein'),
	('Austria', 'Slovakia'),
	('Austria', 'Slovenia'),
	('Austria', 'Switzerland'),
	('Azerbaijan', 'Georgia'),
	('Azerbaijan', 'Russia'),
	('Azerbaijan', 'Turkey'),
	('Belarus', 'Latvia'), 
	('Belarus', 'Lithuania'),
	('Belarus', 'Poland'),
	('Belarus', 'Russia'),
	('Belarus', 'Ukraine'),
	('Belgium', 'France'),
	('Belgium', 'Luxembourg'),
	('Belgium', 'Netherlands'),
	('Bosnia and Herzegovina', 'Croatia'),
	('Bosnia and Herzegovina', 'Montenegro'),
	('Bosnia and Herzegovina', 'Serbia'),
	('Bulgaria', 'Greece'),
	('Bulgaria', 'Macedonia'),
	('Bulgaria', 'Romania'),
	('Bulgaria', 'Serbia'),
	('Bulgaria', 'Turkey'),
	('Croatia', 'Hungary'), 
	('Croatia', 'Montenegro'),
	('Croatia', 'Serbia'),
	('Croatia', 'Slovenia'),
	('Czech Republic', 'Germany'),
	('Czech Republic', 'Poland'),
	('Czech Republic', 'Slovakia'),
	('Denmark', 'Germany'),
	('Estonia', 'Latvia'),
	('Estonia', 'Russia'),
	('Finland', 'Norway'),
	('Finland', 'Sweden'),
	('Finland', 'Russia'),
	('France', 'Germany'),
	('France', 'Italy'),
	('France', 'Luxembourg'),
	('France', 'Monaco'),
	('France', 'Spain'),
	('France', 'Switzerland'),
	('Georgia', 'Russia'),
	('Georgia', 'Turkey'),
	('Germany', 'Luxembourg'),
	('Germany', 'Netherlands'),
	('Germany', 'Poland'),
	('Germany', 'Switzerland'),
	('Greece', 'Turkey'),
	('Greece', 'Macedonia'),
	('Hungary', 'Romania'),
	('Hungary', 'Serbia'),
	('Hungary', 'Slovakia'),
	('Hungary', 'Slovenia'),
	('Hungary', 'Ukraine'),
	('Ireland', 'United Kingdom'),
	('Italy', 'San Marino'),
	('Italy', 'Slovenia'),
	('Italy', 'Switzerland'),
	('Italy', 'Vatican City'),
	('Kosovo', 'Macedonia'),
	('Kosovo', 'Montenegro'),
	('Kosovo', 'Serbia'),
	('Latvia', 'Lithuania'),
	('Latvia', 'Russia'),
	('Liechtenstein', 'Switzerland'),
	('Lithuania', 'Poland'),
	('Lithuania', 'Russia'),
	('Macedonia', 'Serbia'),
	('Moldova', 'Ukraine'),
	('Montenegro', 'Serbia'),
	('Norway', 'Sweden'),
	('Norway', 'Russia'),
	('Poland', 'Russia'),
	('Poland', 'Slovakia'),
	('Poland', 'Ukraine'),
	('Portugal', 'Spain'),
	('Romania', 'Serbia'),
	('Romania', 'Ukraine'),
	('Russia', 'Ukraine'),
	('Ukraine', 'Slovakia');